### ISSUE TITLE
[Bug] Import name is wrong.

### ISSUE THREAD

**Issue by zamu-flowerpot** [aminalaee/uuid-utils#17]
## Expected:

To use `uuid-utils` the README.md mentions to:

```python
import uuid_utils as uuid
```

## Current:

To actually be able to import `uuid-utils`, you need to:

```python
import _uuid_utils as uuid
```

**Comment by aminalaee** [comment]
Bey,
Yes this is already fixed, I will make another release today to fix it.

**Comment by aminalaee** [comment]
This is fixed now.
