### ISSUE TITLE
Does it meets the final specs?

### ISSUE THREAD

**Issue by rettinghaus** [aminalaee/uuid-utils#49]
Since [RFC 9562](https://www.rfc-editor.org/rfc/rfc9562) is final now, I was wondering if this implementation is already compliant with finalized UUID7.

**Comment by aminalaee** [comment]
This library uses the `uuid` crate from Rust but according to their code and docs seems like is is the same implementation: 
https://github.com/uuid-rs/uuid/blob/98fc36df4d3f33669d54f1d7b999888f75d8b71f/src/v7.rs
https://datatracker.ietf.org/doc/html/draft-peabody-dispatch-new-uuid-format-04#section-5.2

**Comment by Devon-Dickson** [comment]
Version 1.9 if the rust crate now supports a counter, so that UUIDs created in the same millisecond are still sortable. Are there plans to upgrade this dependency?

**Comment by aminalaee** [comment]
Sure, I'll try to get it released today or tomorrow.
