### ISSUE TITLE
Incompatible with Django

### ISSUE THREAD

**Issue by rettinghaus** [aminalaee/uuid-utils#50]
It doesn't work correctly as a drop-in replacement with Django. 

I have a uuid field: 

`uuid = models.UUIDField(default=uuid.uuid4(), editable=False)`

If I replace the standard `uuid` module with `uuid_utils` and run stress tests I'll end with a crash at some point with 

> django.core.exceptions.ValidationError: ['“771202f8-71eb-483b-b553-c3f9d9ef216a” is not a valid UUID.']

It happens somewhere when calling the standard package with 

> AttributeError: 'uuid_utils.UUID' object has no attribute 'replace'

Any idea what to do?

**Comment by aminalaee** [comment]
Even though the functionality of the `uuid_utils.UUID` is the same as standard library, chances are for example the Django code checks `if isinstance(obj, uuid.UUID)` so it won't work in some cases.
If you want to be 100% sure it works you should check the compat module: https://github.com/aminalaee/uuid-utils?tab=readme-ov-file#compat-module

**Comment by rettinghaus** [comment]
Yes, in general it could help to read the readme completely… Thanks!
