### ISSUE TITLE
Bug: critical

### ISSUE THREAD

**Issue by SpaceIgor** [aminalaee/uuid-utils#63]
I have in db correct UUID: 
When i got request to my server, I validate data 

from uuid import UUID

class ExampleClass(BaseModel):
    id: UUID        ("id": "cc81d2dd-1066-4840-8c51-bb24d3276ae6") - my id for example
  
  and i have next error
        "Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `l` at 2"

**Comment by aminalaee** [comment]
I don't really understand the problem. Can you post a formatted example code to reproduce this?
