### ISSUE TITLE
Seed possibiltiy

### ISSUE THREAD

**Issue by FranzForstmayr** [aminalaee/uuid-utils#64]
Is there a way to seed the random generator to reproducible results for test purposes?

**Comment by aminalaee** [comment]
I never thought about that. Isn't it possible the way we would seed stdlib uuid module?

**Comment by FranzForstmayr** [comment]
stdlib has no uuid7.

In your library I can pass either bytes or the timestamp, not both, so I think it's not possible atm. 
However I think I'll change for uuid4 for testing.
