### ISSUE TITLE
typing doesn't match impl

### ISSUE THREAD

**Issue by trim21** [aminalaee/uuid-utils#69]
```python
import uuid_utils
from uuid_utils import uuid7


print(uuid_utils.__version__) # 0.9.0

u = uuid7()

print(u, u.is_safe)
```

https://github.com/aminalaee/uuid-utils/blob/926d2c26154126d31dcb7f9956b4f2400422be56/python/uuid_utils/__init__.pyi#L85-L86

```
    print(u, u.is_safe)
             ^^^^^^^^^
AttributeError: 'uuid_utils.UUID' object has no attribute 'is_safe'
```

**Comment by trim21** [comment]
also kwargs `is_safe` doesn't exist 

https://github.com/aminalaee/uuid-utils/blob/926d2c26154126d31dcb7f9956b4f2400422be56/python/uuid_utils/__init__.pyi#L83

**Comment by trim21** [comment]
and after testing, I think it should return `SafeUUID.unsafe` or `SafeUUID.unknown`

```
import os

from uuid_utils import uuid1


print(uuid1(), flush=True)
os.fork()
u = uuid1()
print(u)
```

also `SafeUUID` doesn't exists in `uuid_utils/__init__.py`, but exists in `uuid_utils/__init__.pyi`

**Comment by trim21** [comment]
I know nothing about uuid-rs, is it safe?

**Comment by aminalaee** [comment]
Adding them can't be hard. I will get to it for the next version.

**Comment by trim21** [comment]
looks like it's difficult to import some python variable and use it in pyo3...

**Comment by trim21** [comment]
https://github.com/aminalaee/uuid-utils/pull/70
